import Header from "@/components/Header";
import Footer from "@/components/Footer";

const Terms = () => {
  return (
    <div className="min-h-screen bg-background">
      <Header />
      <main className="pt-24 pb-16">
        <div className="container mx-auto px-4 max-w-4xl">
          <h1 className="text-4xl font-bold text-foreground mb-4">
            Terms & Conditions
          </h1>
          <p className="text-lg text-muted-foreground mb-2">
            Asta – Legal SaaS
          </p>
          <p className="text-muted-foreground mb-8">Last updated: 2.02.2026</p>

          <div className="space-y-8">
            <section>
              <h2 className="text-2xl font-semibold text-foreground mb-4">
                1. Scope of Agreement
              </h2>
              <p className="text-muted-foreground mb-3">
                These Terms govern access to and use of the Asta SaaS platform
                ("Service").
              </p>
              <p className="text-muted-foreground mb-3">
                The Service is provided exclusively for professional use by law
                firms and legal professionals.
              </p>
              <p className="text-muted-foreground">
                By using the Service, you agree to these Terms.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-semibold text-foreground mb-4">
                2. Eligibility & Authority
              </h2>
              <p className="text-muted-foreground mb-3">You confirm that:</p>
              <ul className="list-disc pl-6 text-muted-foreground space-y-2">
                <li>
                  You are a qualified legal professional or an authorized
                  representative of a law firm
                </li>
                <li>You have authority to bind your organization</li>
              </ul>
            </section>

            <section>
              <h2 className="text-2xl font-semibold text-foreground mb-4">
                3. Nature of the Service – No Legal Advice
              </h2>
              <p className="text-muted-foreground mb-3">
                Asta does not provide legal advice.
              </p>
              <p className="text-muted-foreground mb-3">
                The Service functions solely as a decision-support and
                assistance tool.
              </p>
              <p className="text-muted-foreground mb-3">
                Any outputs generated by the Service:
              </p>
              <ul className="list-disc pl-6 text-muted-foreground space-y-2 mb-3">
                <li>Are informational only</li>
                <li>
                  Do not constitute legal advice, opinions, or recommendations
                </li>
                <li>
                  Do not replace professional judgment or independent legal
                  analysis
                </li>
              </ul>
              <p className="text-muted-foreground">
                All legal decisions, advice, and actions remain your sole
                responsibility.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-semibold text-foreground mb-4">
                4. AI-Assisted Outputs
              </h2>
              <p className="text-muted-foreground mb-3">
                The Service may generate summaries, classifications,
                suggestions, or insights using automated or AI-assisted
                processes.
              </p>
              <p className="text-muted-foreground mb-3">You acknowledge that:</p>
              <ul className="list-disc pl-6 text-muted-foreground space-y-2">
                <li>
                  Outputs may be incomplete, inaccurate, or contextually
                  incorrect
                </li>
                <li>
                  Asta does not guarantee correctness, completeness, or
                  suitability
                </li>
                <li>All outputs must be independently reviewed before use</li>
              </ul>
            </section>

            <section>
              <h2 className="text-2xl font-semibold text-foreground mb-4">
                5. No Reliance & Disclaimer of Responsibility
              </h2>
              <p className="text-muted-foreground mb-3">
                You agree not to rely solely on outputs generated by the
                Service.
              </p>
              <p className="text-muted-foreground mb-3">
                Asta accepts no responsibility or liability for:
              </p>
              <ul className="list-disc pl-6 text-muted-foreground space-y-2">
                <li>Decisions made based on AI-assisted outputs</li>
                <li>
                  Claims, losses, or damages arising from reliance on the
                  Service
                </li>
                <li>Regulatory, professional, or ethical breaches</li>
              </ul>
            </section>

            <section>
              <h2 className="text-2xl font-semibold text-foreground mb-4">
                6. Customer Responsibilities
              </h2>
              <p className="text-muted-foreground mb-3">
                You are responsible for:
              </p>
              <ul className="list-disc pl-6 text-muted-foreground space-y-2">
                <li>Uploading data lawfully</li>
                <li>
                  Ensuring client notices and consents where required
                </li>
                <li>
                  Compliance with professional conduct rules and regulations
                </li>
              </ul>
            </section>

            <section>
              <h2 className="text-2xl font-semibold text-foreground mb-4">
                7. Data Ownership & Processing
              </h2>
              <ul className="list-disc pl-6 text-muted-foreground space-y-2">
                <li>You retain full ownership of all uploaded data</li>
                <li>Asta acts solely as a Data Processor</li>
                <li>A Data Processing Agreement forms part of these Terms</li>
              </ul>
            </section>

            <section>
              <h2 className="text-2xl font-semibold text-foreground mb-4">
                8. Security Commitment
              </h2>
              <p className="text-muted-foreground">
                Asta maintains appropriate technical and organizational measures
                to protect data and will notify customers of personal data
                breaches in accordance with applicable law.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-semibold text-foreground mb-4">
                9. Subscriptions & Fees
              </h2>
              <ul className="list-disc pl-6 text-muted-foreground space-y-2">
                <li>Access is subscription-based</li>
                <li>Fees are billed in advance</li>
                <li>
                  Payments are non-refundable except where required by law
                </li>
                <li>We may suspend access for non-payment</li>
              </ul>
            </section>

            <section>
              <h2 className="text-2xl font-semibold text-foreground mb-4">
                10. Acceptable Use
              </h2>
              <p className="text-muted-foreground mb-3">You must not:</p>
              <ul className="list-disc pl-6 text-muted-foreground space-y-2">
                <li>Reverse engineer or attempt to bypass security</li>
                <li>Use the Service unlawfully</li>
                <li>Interfere with system integrity or availability</li>
              </ul>
            </section>

            <section>
              <h2 className="text-2xl font-semibold text-foreground mb-4">
                11. Availability
              </h2>
              <p className="text-muted-foreground mb-3">
                The Service is provided on an "as available" basis.
              </p>
              <p className="text-muted-foreground">
                Maintenance, updates, or downtime may occur.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-semibold text-foreground mb-4">
                12. Limitation of Liability
              </h2>
              <p className="text-muted-foreground mb-3">
                To the maximum extent permitted by law:
              </p>
              <ul className="list-disc pl-6 text-muted-foreground space-y-2 mb-3">
                <li>
                  Asta is not liable for indirect or consequential losses
                </li>
                <li>
                  Total liability is capped at fees paid in the previous 12
                  months
                </li>
              </ul>
              <p className="text-muted-foreground">
                Nothing limits liability for fraud or willful misconduct.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-semibold text-foreground mb-4">
                13. Indemnification
              </h2>
              <p className="text-muted-foreground mb-3">
                You agree to indemnify Asta against claims arising from:
              </p>
              <ul className="list-disc pl-6 text-muted-foreground space-y-2">
                <li>Unlawful data uploads</li>
                <li>Breach of professional obligations</li>
                <li>Misuse of the Service</li>
              </ul>
            </section>

            <section>
              <h2 className="text-2xl font-semibold text-foreground mb-4">
                14. Termination
              </h2>
              <p className="text-muted-foreground mb-3">
                Either party may terminate the agreement.
              </p>
              <p className="text-muted-foreground mb-3">Upon termination:</p>
              <ul className="list-disc pl-6 text-muted-foreground space-y-2">
                <li>Access ends immediately</li>
                <li>Data handling follows the Privacy Policy</li>
              </ul>
            </section>

            <section>
              <h2 className="text-2xl font-semibold text-foreground mb-4">
                15. Governing Law
              </h2>
              <p className="text-muted-foreground mb-3">
                These Terms are governed by the laws of England and Wales.
              </p>
              <p className="text-muted-foreground">
                Courts of England and Wales have exclusive jurisdiction.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-semibold text-foreground mb-4">
                16. Contact
              </h2>
              <p className="text-muted-foreground">
                Email:{" "}
                <a
                  href="mailto:hello@useasta.com"
                  className="text-primary hover:underline"
                >
                  hello@useasta.com
                </a>
              </p>
            </section>
          </div>
        </div>
      </main>
      <Footer />
    </div>
  );
};

export default Terms;
